# Generated by Django 3.0.6 on 2020-05-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20200508_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
